### ISSUE TITLE
Unified deep linking cannot achieve deferred deep linking

### ISSUE THREAD

**Issue by samchanCHS** [AppsFlyerSDK/appsflyer-onelink-ios-sample-apps#3]
[This guide](https://support.appsflyer.com/hc/en-us/articles/207032096#1-implementing-deferred-deep-linking) saids that Unified deep linking should be a way to implement deferred deep linking, however it didn't work as described after I used the code in this repo.

Expected Behavior:
1. App not installed
2. Open the link
3. Install the app
4. The app should jump to deep link page right after launching

My testing approach follows instructions [here](https://support.appsflyer.com/hc/en-us/articles/207032096#2-testing), if I am using [Deferred deep linking approach ](https://dev.appsflyer.com/docs/deferred-deep-linking)(`onConversionDataSuccess`) it will work, as I can see the `deep_link_value` outputted in the console, but not working for [Unified deep linking approach](https://dev.appsflyer.com/docs/ios-unified-deep-linking) (didResolveDeepLink), and I saw the console has outputted `Deep link not found` at https://github.com/AppsFlyerSDK/appsflyer-onelink-ios-sample-apps/blob/a96399329a369b30263ea4f8cc4558029ea603b3/swift/basic_app/basic_app/AppDelegate.swift#L107-L108

**Comment by samchanCHS** [comment]
Did some digging and testing today, I found that the Unified deep linking can work in Simulators, but for a real device, I could not get it to work, even if I have registered the device into the portal.

**Comment by liaz-af** [comment]
@samchan1995 I'm sorry for very late reply.
If this is still relevant, can you pls post here the data you did get get `onConversionDataSuccess`?
Thanks

**Comment by ilonashub** [comment]
I am experiencing the same issue with my app as well, @samchan1995 did you manage to get it working with the UDL on a real device?
